### Write Data to InfluxDB
POST http://localhost:8080/influxdb/write
Content-Type: application/json

{
  "measurement": "equipment",
  "tags": {
    "name": "포크레인",
    "prodId": "포크레인A"
  },
  "fields": {
    "temperature": 70.0,
    "use": true
  }
}

###
POST http://localhost:8080/influxdb/query
Content-Type: application/json

{
  "measurement": "home",
  "start": "-1d",
  "tags": {
    "location": "west",
    "simple": "test"
  },
  "fields": ["field1"],
  "values": [5]
}