### Write Data to InfluxDB
POST http://localhost:8080/influxdb/write
Content-Type: application/json

{
  "measurement": "home",
  "tags": {
    "location": "west",
    "simple": "test"
  },
  "fields": {
    "field1": 5,
    "field2": 5.0,
    "field3": 5
  }
}

###
POST http://localhost:8080/influxdb/query
Content-Type: application/json

{
  "measurement": "home",
  "start": "-1d",
  "tags": {
    "location": "west",
    "simple": "test"
  },
  "fields": ["field1"],
  "values": [5]
}