### publish
GET {{url}}/publish?message=hello23
Content-Type: application/json

### publish2
POST {{url}}/publish
Content-Type: application/json

{
  "topic": "b",
  "message": "{\"title\" : \"title11\", \"content\": \"content22\"}"
}

### subscribe
POST {{url}}/subscribe?topic=f
Content-Type: application/json

### subscribed
GET {{url}}/subscribed
Content-Type: application/json
