server:
  port: 10040
  shutdown: graceful
management:
  server:
    port: 10041
spring:
  profiles:
    include:
    group:
      local:
    active: local
  application:
    name: influxV3
  lifecycle:
    timeout-per-shutdown-phase: 15s
